# Generated by Django 5.2.12 on 2026-03-23 14:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100, verbose_name='Хозяева')),
                ('away_team', models.CharField(max_length=100, verbose_name='Гости')),
                ('match_date', models.DateTimeField(verbose_name='Дата и время матча')),
                ('price', models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='Цена билета')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['match_date'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер ряда')),
                ('seat_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер места')),
                ('section', models.CharField(default='Центральный', max_length=50, verbose_name='Сектор')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('total_seats', models.IntegerField(verbose_name='Всего мест')),
                ('rows', models.IntegerField(default=10, verbose_name='Количество рядов')),
                ('seats_per_row', models.IntegerField(default=20, verbose_name='Мест в ряду')),
            ],
            options={
                'verbose_name': 'Стадион',
                'verbose_name_plural': 'Стадионы',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(editable=False, max_length=10, unique=True, verbose_name='Код бронирования')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('customer_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^\\+?[0-9\\s\\-\\(\\)]+$')], verbose_name='Телефон')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('status', models.CharField(choices=[('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('expired', 'Просрочено')], default='confirmed', max_length=20, verbose_name='Статус')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата бронирования')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.match', verbose_name='Матч')),
                ('seats', models.ManyToManyField(to='bookings.seat', verbose_name='Места')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-booking_date'],
            },
        ),
        migrations.AddField(
            model_name='seat',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.stadium', verbose_name='Стадион'),
        ),
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.stadium', verbose_name='Стадион'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('stadium', 'row_number', 'seat_number')},
        ),
    ]
