# Generated by Django 5.2.12 on 2026-03-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='notes',
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default='confirmed', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='match',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row_number',
            field=models.IntegerField(verbose_name='Номер ряда'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.IntegerField(verbose_name='Номер места'),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='rows',
            field=models.IntegerField(default=10, verbose_name='Ряды'),
        ),
    ]
